# Generated by Django 5.2.8 on 2025-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=200, verbose_name='Página visitada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visita')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha'],
            },
        ),
    ]
